#!/usr/bin/env sh

options=(
    style=round
    width=6.0
    hidpi=on
    active_color=0xffe1e3e4  # Roxo (Foco)
    inactive_color=0xff494d64 # Cinza (Inativo)
    radius=12.0
)

borders "${options[@]}"
